### ISSUE TITLE
frameInfo is undefined in chrome , in nodejs env is object

### ISSUE THREAD

**Issue by xushimin** [benwiley4000/gif-frames#10]

**Comment by benwiley4000** [comment]
@xushimin thanks for flagging. I think this is because I haven't released the update that includes frameInfo yet. I appreciate the reminder!

But are you saying that frameInfo *is* defined when you run in nodejs?

**Comment by oxayotl** [comment]
I had a similar problem, but it turned out that I was using https://unpkg.com/gif-frames@0.4.0?main=bundled-min as advertised here: https://www.npmjs.com/package/gif-frames, so the 0.4 version instead of the 1.0 version. After switching to https://unpkg.com/gif-frames?main=bundled-min it worked alright! Maybe that's what happened to xushimin?

**Comment by benwiley4000** [comment]
@oxayotl what problem did you have exactly?

I'm confused how this could be working at all since I haven't released this feature yet 😄

**Comment by xushimin** [comment]
<script src="https://unpkg.com/gif-frames@0.4.0?main=bundled"></script> 
this link may not up to date,

because when i using code like this:
var gifFrames = require('gif-frames');
i can get frameInfo both nodejs and chrome browser

**Comment by benwiley4000** [comment]
wow, looks like I pushed a new update to npm, and never pushed to github, and forgot about it!! I'll try to update github soon. Must have been tired! And glad your issue is fixed!
