### ISSUE TITLE
how to working in browser without XMLHttpRequest

### ISSUE THREAD

**Issue by zlzdp** [benwiley4000/gif-frames#14]

**Comment by benwiley4000** [comment]
Hey @zlzdp, could you explain a bit more? Are you trying to get this to work on a super old browser that doesn't have XMLHttpRequest? What is your use case?

**Comment by zlzdp** [comment]
I can  get ArrayBuffer for gif file, and pass ArrayBuffer to gif-frames.js,
```
var buffer = Buffer.from(arrayBuffer)
gifFrames({ url: buffer, frames: 'all' })

// gif-frames throw error: DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
```
the Buffer module for browser: https://www.npmjs.com/package/buffer
can you support ArrayBuffer gif data in browser? not get gif data from XMLHttpRequest ajax request.

thank you.

**Comment by zlzdp** [comment]
I want make gif-frames.js working with ArrayBuffer  and FileReader(read data from <input type=file>). 
gif-frames.js only supported get gif data from XMLHttpRequest request in browser.
thank you.

**Comment by benwiley4000** [comment]
Thanks for explaining!

The get-pixels package, used under the hood, supposedly supports in-memory buffers Node.js style. https://www.npmjs.com/package/get-pixels

I suspect the reason your code doesn't work is because you're using the npm buffer package instead of the `Buffer` global built into browserify or webpack. See this line in get-pixels which checks if you passed a Buffer: https://github.com/scijs/get-pixels/blob/master/dom-pixels.js#L126

**Comment by benwiley4000** [comment]
@zlzdp can you please let me know if this works for you? Thanks! :)

**Comment by benwiley4000** [comment]
Alternatively if you need to use that package you could define it as a global:

```js
window.Buffer = require('buffer')
```

**Comment by zlzdp** [comment]
I tried other way make it working,
```
fileReader.readAsDataURL(file)
// get dataURL
gifFrames({ url: dataURL})
// it can get all frames of gif image.
```
thank you.

**Comment by benwiley4000** [comment]
If this works fine for you, great! For a sufficiently large file this won't work since data urls have a size limit - if you run into that you can try the other method I suggested.

Cheers - I'll close the issue now.
