### ISSUE TITLE
is it production ready?

### ISSUE THREAD

**Issue by sido420** [benwiley4000/gif-frames#7]
I wanted to use it in my project but not sure.

**Comment by benwiley4000** [comment]
Hey @sido420, sorry for the late reply.

Not sure how to answer your question - but I can point you to the [dependents page](https://github.com/benwiley4000/gif-frames/network/dependents), which shows that 4 npm modules and 31 open source projects on GitHub rely on gif-frames, with no new issues reported since last December.

So I'd say it's a pretty safe bet it can help with your use case, although I'm always happy to look into bugs if you find one!

**Comment by benwiley4000** [comment]
I'll close this for now - let me know if you have other questions.
