### ISSUE TITLE
interframe delay info?

### ISSUE THREAD

**Issue by webarchymeta** [benwiley4000/gif-frames#8]
Is there any way to extract the inter-frame delay information, which could be helpful in replaying the animation faithfully?

**Comment by benwiley4000** [comment]
@webarchymeta this is a good idea although I would veer toward suggesting using an outside utility unless we have a good way to extract the delay info from the gif in a few lines of code. I'm not familiar enough with the GIF format to know how to do this off the top of my head, but I would be open to pull requests!

**Comment by benwiley4000** [comment]
For any pull requests, I would appreciate if we could avoid adding more 3rd party dependencies.

**Comment by Snelius30** [comment]
Hey guys. I've looked in ur code and i guess best solution would be PR for the **get-pixels** to provide us related method/info or access to internal **reader** object. If you look the **get-pixels**, u can see we have usage of **omggif** module to obtain GIF meta info and data (For example for DOM: https://github.com/scijs/get-pixels/blob/master/dom-pixels.js#L32). And we can get all we need with **GifReader** interface because it has **frameinfo** method (https://github.com/deanm/omggif/blob/master/omggif.js#L524) with delay info (https://github.com/deanm/omggif/blob/master/omggif.js#L502). Well, we can use **omggif** in direct to get _again_ that info for the frames but it will be overhead and bad style. Also we can get delay info in direct from the file data, but we need to get this one _again_ (http,fs) which bad solution too :)

**Comment by benwiley4000** [comment]
@Snelius30 get-pixels isn't maintained very actively anymore, so I think it would be best to make the change directly here. Considering we're parsing the GIF for frames I don't think the additional overhead of using omggif directly to parse metadata is going to be disastrous. Since get-pixels uses omggif I'd be fine relying on the same version and making it a direct dependency of gif-frames.

What do you think? :)

**Comment by benwiley4000** [comment]
Hm, I just took a look at omggif and I see what you're saying - it pretty much parses the whole thing. If you want to make a PR to get-pixels I think that is a good idea as you mentioned before. However I wouldn't necessarily count on it being merged quickly. We may want to publish the fork.

**Comment by benwiley4000** [comment]
Ha, just remembered I'm a github collaborator on get-pixels... which means I can merge the PR if it's good. I don't have publish access though, so I'll have to bug the maintainer about it. :smile:

**Comment by Snelius30** [comment]
Well, as a solution i think we can bring the get-pixels code here because its a single file module with MIT license and add what we need. If it has not a maintained anymore.

**Comment by benwiley4000** [comment]
Sorry, want to make sure you saw my last message. I can get it merged at least to github and we can publish a temporary fork if needed.

**Comment by Snelius30** [comment]
Ah OK. Yep, u are to fast ;) Got it. It would be nice to PR to the proper place.

**Comment by benwiley4000** [comment]
@Snelius30 are you interested in working on that?

**Comment by Snelius30** [comment]
Yea, i will handle it. I need to finish a couple of other issues before. I believe i can take it today.

**Comment by Snelius30** [comment]
Well, we have framesInfo now as getPixels() CB param now (pls check my get-pixels PR). Where we need to store the info?

**Comment by benwiley4000** [comment]
@Snelius30 thank you, I just reviewed both of your PRs. This is looking great!

**Comment by benwiley4000** [comment]
@Snelius30 @webarchymeta this feature has been released with version 1.0.0.

**Comment by webarchymeta** [comment]
great, thanks!
